name: GH-Pages deploy

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - run: curl -L -O https://b.enjam.info/panam/styling.css
      - run: echo "::set-env name=FILELIST::$(cat pandoc_list.txt)"
      - uses: docker://pandoc/core:latest
        with:
          args: ${{ env.FILELIST }} -o index.html -s --toc -w html5 --css=styling.css
      - uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: "output/"
          GH_PAT: ${{ secrets.GH_PAT }}

