name: GH-Pages deploy

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - run: curl -L -O https://b.enjam.info/panam/styling.css
      - uses: docker://pandoc/code:latest
        with:
          args: $(cat pandoc_list.txt) -o index.html -s --toc -w html5 --css=styling.css
      - uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: "output/"
          GH_PAT: ${{ secrets.GH_PAT }}

